DROP TABLE PRICES IF EXISTS;

CREATE TABLE PRICES (
  BRAND_ID    INTEGER,
  START_DATE  TIMESTAMP,
  END_DATE    TIMESTAMP,
  PRICE_LIST  INTEGER,
  PRODUCT_ID  INTEGER,
  PRIORITY    TINYINT,
  PRICE       NUMERIC(20, 2),
  CURR VARCHAR(3)
);

CREATE INDEX prices_PK ON PRICES (BRAND_ID, START_DATE, END_DATE, PRODUCT_ID, PRIORITY);

